org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.22)
neo_version=21.10.64
neo_version_range=[21,)
loader_version_range=[4,)

mod_group_id=top.untoldstudio.rimeui.neoforge
mod_authors=oiiacat
mod_description=A UI Lib